


#ifndef H_E_HELP
#define H_E_HELP


/*
enum
{
HELP_NONE, // does nothing when clicked

HELP_MISSION_MENU,
HELP_ADVANCED_MISSION_MENU,
HELP_TUTORIAL_MENU,
HELP_USE_SYSFILE,
HELP_LOAD,
HELP_LOAD_GAMEFILE,
HELP_OPTIONS,
HELP_MAIN_EXIT,

HELP_SETUP_START,
HELP_SETUP_PLAYERS,
HELP_SETUP_TURNS,
HELP_SETUP_MINUTES,
HELP_SETUP_PROCS,
HELP_SETUP_W_BLOCK,
HELP_SETUP_H_BLOCK,
HELP_SETUP_BACK_TO_START,
HELP_SETUP_PLAYER_NAME,
HELP_SETUP_SAVE_GAMEFILE,

HELP_TUTORIAL_1,
HELP_TUTORIAL_2,
HELP_TUTORIAL_3,
HELP_TUTORIAL_4,
HELP_TUTORIAL_BACK,
HELP_MISSION,
HELP_MISSIONS_BACK,
HELP_ADVANCED_MISSION,
HELP_ADVANCED_MISSIONS_BACK,

HELP_TEMPLATE_OPEN_FILE,
HELP_TEMPLATE_IMPORT,
HELP_TEMPLATE_CLEAR,
HELP_TEMPL_PROC,
HELP_TEMPL_SYSTEM,
HELP_TEMPL_OPERATOR,
HELP_TEMPL_DELEGATE,
HELP_TEMPL_OBSERVER,
HELP_TEMPL_DEFAULT_PROC,
HELP_TEMPL_DEFAULT_OPERATOR,
HELP_TEMPL_DEFAULT_OBSERVER,
HELP_TEMPL_DEFAULT_DELEGATE,

HELP_TURNFILE_BUTTON,

HELP_MODE_BUTTON_EDITOR,
HELP_MODE_BUTTON_TEMPLATES,
HELP_MODE_BUTTON_PROGRAMS,
HELP_MODE_BUTTON_SYSMENU,
HELP_MODE_BUTTON_CLOSE,

//HELP_SUBMENU_NEW,
HELP_SUBMENU_OPEN,
HELP_SUBMENU_SAVE,
HELP_SUBMENU_SAVE_AS,
//HELP_SUBMENU_CLOSE_FILE,
HELP_SUBMENU_UNDO,
HELP_SUBMENU_REDO,
HELP_SUBMENU_CUT,
HELP_SUBMENU_COPY,
HELP_SUBMENU_PASTE,
HELP_SUBMENU_CLEAR,
HELP_SUBMENU_FIND,
HELP_SUBMENU_FIND_NEXT,
HELP_SUBMENU_TEST_COMPILE,
HELP_SUBMENU_COMPILE_BCODE,
HELP_SUBMENU_COMPILE_LOCK,
//HELP_SUBMENU_BUILD_ASM,
//HELP_SUBMENU_CRUNCH_ASM,
//HELP_SUBMENU_CONVERT_BCODE,
//HELP_SUBMENU_IMPORT_BCODE,

HELP_SYSMENU_PAUSE,
HELP_SYSMENU_HALT,
HELP_SYSMENU_QUIT,
HELP_SYSMENU_RETURN_TO_MAIN,
HELP_SYSMENU_QUIT_CONFIRM,
HELP_SYSMENU_SAVE,

HELP_STRINGS // must be last
}; // enums to go in header file so other files can use them
*/
//void print_help(int help_type);
void editor_help_click(struct source_edit_struct* se, int source_line, int source_pos);
void print_help_string(const char* help_str);

#endif
